-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- Normal mode: toggle terminal
-- vim.keymap.set("n", "<leader>t", "<cmd>ToggleTerm<cr>", {
--   noremap = true,
--   silent = true,
--   desc = "Toggle terminal",
-- })
--
-- -- Terminal mode: exit to normal then toggle
-- vim.keymap.set("t", "<leader>t", "<C-\\><C-n><cmd>ToggleTerm<cr>", {
--   noremap = true,
--   silent = true,
--   desc = "Toggle terminal",
-- })
